### ISSUE TITLE
Crash when close to final castle

### ISSUE THREAD

**Issue by Dagfinnr45** [TeamTwilight/twilightforest-fabric#173] opened 2023-02-03 06:24 UTC
### Fabric Loader Version

0.14.12

### Fabric API Version

0.73

### Twilight Forest Version

4.2.310 + 4.2.333

### Crash Report (if applicable)

<script src="https://gist.github.com/Dagfinnr45/7893971626b85d9ecb38334093be2fe3.js"></script>

### Steps to Reproduce

when getting to close to the final castle, the game crash.
tried with an older version of twilight, same thing happen.
after the crash, each time i go to the castle, it crash. if i'm far, I can play with no problem.

### What You Expected

no crash?

### What Happened Instead

a crash

### Additional Details

i don't have optifine or any mod close to it.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-02-03 06:25
duplicate of #140

**Closed by GizmoTheMoonPig** 2023-02-03 06:25 UTC
Labels: bug

**Comment by Binkstr** [comment] 2023-02-28 02:17
experienced the same issue, found it had an issue generating light in the chunk, and deleted and regenerated the chunk but the problem persists.
