### ISSUE TITLE
Crash at start of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [TeamTwilight/twilightforest-fabric#84] opened 2022-06-16 21:57 UTC
### Fabric Loader Version

0.14.7

### Fabric API Version

0.56.0+1.18.2

### Twilight Forest Version

4.1.238

### Client Log

https://bytebin.lucko.me/YiinKD8uZN

### Steps to Reproduce

1. Download https://www.curseforge.com/minecraft/modpacks/deathdusk
2. Install Twilight Forest
3. Start it
4. ???
5. Profit

### What You Expected

That i can play twilight forest

### What Happened Instead

It crashed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [ ] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TheButterbrotMan** [comment] 2022-06-16 21:58
https://github.com/TeamTwilight/twilightforest-fabric/issues/70

**Comment by AlphaMode** [comment] 2022-06-16 22:23
Duplicate of #81 the problem is additionalbanners this crash is completely their fault open a issue on there github

**Closed by AlphaMode** 2022-06-16 22:23 UTC
Labels: bug
