### ISSUE TITLE
Game crashes when using the uncrafting table.

### ISSUE THREAD

**Issue by Poke097** [TeamTwilight/twilightforest-fabric#130] opened 2022-11-03 21:59 UTC
### Fabric Loader Version

0.14.10

### Fabric API Version

fabric-api-0.64.0+1.19.2

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.301

### Client Log

https://gist.github.com/Poke097/5165ad4f1c7132c68abab47ae9b91e75

### Crash Report (if applicable)

https://gist.github.com/Poke097/a5f592cf4e9c0c45f4982b9c28f947cb

### Steps to Reproduce

1. Make a Uncrafting Table, or spawn one in.

2. Place a item inside the table.

3. Click on the table area to try and recover items from the uncrafting table.

4. Game exits to "Saving World" and completely closes the game.

### What You Expected

I was under the impression that it would give me my diamonds back, when placing a diamond axe in the table.

### What Happened Instead

Yet when I tried to take the uncrafted items back, it would crash my game.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2022-12-11 20:51
this is caused by Luggage loading an older version of the tags due to the version number technically being higher. Should be fixed in dev

**Closed by TropheusJ** 2022-12-11 20:51 UTC
Labels: bug
