### ISSUE TITLE
Crash related to the final_castle structure

### ISSUE THREAD

**Issue by purejosh** [TeamTwilight/twilightforest-fabric#160] opened 2023-01-17 06:40 UTC
### Fabric Loader Version

0.14.11

### Fabric API Version

0.70.0+1.19.2

### Twilight Forest Version

4.2.333

### Client Log

https://gist.github.com/purejosh/af1b9db422b87ac75433902f3b94a90e

### Crash Report (if applicable)

https://gist.github.com/purejosh/9785404cf428d723514c9219f65281e6

### Steps to Reproduce

1. Be in the Twilight
2. Come close to the final_castle structure
3. Crash (sorry, I actually can't tell what's causing it)

### What You Expected

not to crash. 

### What Happened Instead

crashes. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2023-01-17 14:20
Duplicate of #140

**Closed by TropheusJ** 2023-01-17 14:20 UTC
Labels: bug

**Comment by purejosh** [comment] 2023-01-17 15:35
Whoops... Didn't see #140, sorry about that.
