### ISSUE TITLE
Server crashes with placement error

### ISSUE THREAD

**Issue by Lil2sons1** [TeamTwilight/twilightforest-fabric#180] opened 2023-03-10 06:01 UTC
Fabric Loader version: fabric-loader-0.14.13-1.19.2
Fabric API version: Fabric API 0.73.2+1.19.2
Twilight Forest version: twilightforest-fabric-1.19.2-4.2.335
Link to crash log: https://gist.github.com/Lil2sons1/0a2947152c68e5335813244aa8b67a01
Steps to reproduce:
1. Enter twilight forest
2. Walk to final area
3. Go to center of castle (or respawn in it)

What I expected to happen: I can walk around and to the castle

What happened instead: I went to the final castle and crashed the server with the log above. Restarting and respawning repeats the issue. 

I have seen this issue occur with C2ME, but I do not have C2ME, so I do not believe this to be a dupe. Sorry if it is.

**Comment by GizmoTheMoonPig** [comment] 2023-03-10 06:43
Duplicate of #140

**Closed by GizmoTheMoonPig** 2023-03-10 06:43 UTC
