### ISSUE TITLE
1.19.2 Fabric Server-Crash: IllegalArgumentException: Bound must be positive in TowerWingComponent and FinalCastleMazeTower13Component

### ISSUE THREAD

**Issue by Boroso** [TeamTwilight/twilightforest-fabric#193] opened 2023-05-08 18:23 UTC
### Fabric Loader Version

fabric - 0.14.19

### Fabric API Version

fabric-api-0.76.0+1.19.2

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.357

### Crash Report (if applicable)

https://gist.github.com/Boroso/81f08bb10d1f08e8135800b3e7a2e373

### Steps to Reproduce

1. Set up a server with Fabric 1.19.2, Twilight Forest, and Chunky mod.
2. Start pre-generating chunks in the Twilight Forest dimension using the fabric Chunky mod.
3. Observe the server crash at a specific generation point.

/chunky start (insert fabric dimension) square 0 0 10000 10000

### What You Expected

No crashes, a natural twilight pre-generation using chunky mod.

### What Happened Instead

While using the Chunky mod to pre-generate chunks in the Fabric 1.19.2 Twilight Forest dimension, my server crashed at a specific generation point. The expected behavior was for the server to continue pre-generating the chunks without any issues.

/chunky start (insert fabric dimension) square 0 0 10000 10000

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2023-05-12 00:17
duplicate of #140

**Closed by TropheusJ** 2023-05-12 00:17 UTC
Labels: bug
