### ISSUE TITLE
Urghast battle seems to cause more fire then should be

### ISSUE THREAD

**Issue by 12thDimension** [TeamTwilight/twilightforest-fabric#141] opened 2022-11-21 02:00 UTC
### Fabric Loader Version

0.14.10

### Fabric API Version

0.64.0+1.19.2

### Twilight Forest Version

4.2.301

### Steps to Reproduce

1. Launch BetterMC for Fabric on 1.19.2 Version 10 of the modpack
2. Defeat all bosses prior to Urghast
3. Defeat the Urghast
4. Look at the leaves of the dark forest

### What You Expected

I expected some fire on the leaves

### What Happened Instead

Approximately all leaves around the Urghast Tower in a radius of ma
![image](https://user-images.githubusercontent.com/40957185/202944814-bb5504d5-d5b0-4013-9626-d564cfbf1aa3.png)
ybe 200 Blocks were on fire.

### Additional Details

This is my first bug report ever. I didnt take screenshots then so no proof. Maybe there was something I did wrong, like spending too much time there and having a lot of ghasts shoot. Anyway this could have been unplayable on a worse pc as there was really a lot of fire.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by varencilator** [comment] 2022-11-24 21:09
This happened for me in 4.2.299 as well. I just thought it was intended

**Comment by TropheusJ** [comment] 2022-12-11 19:31
fixed by https://github.com/TeamTwilight/twilightforest-fabric/commit/dc00f16ea6a54a28ab736c807a13f227c3c3593b

**Closed by TropheusJ** 2022-12-11 19:31 UTC
Labels: bug
