### ISSUE TITLE
TF crashes with the most recent version of fabric api 

### ISSUE THREAD

**Issue by SticksS123** [TeamTwilight/twilightforest-fabric#78] opened 2022-06-14 00:26 UTC
### Fabric Loader Version

0.14.7

### Fabric API Version

0.56.0

### Twilight Forest Version

4.1.235

### Client Log

https://gist.github.com/SticksS123/28b576316f1e4c691ccdd27d1e2bd787

### Steps to Reproduce

1.-install TF using the latest version of fabric loader and api

2.- start the game

3.-crash

### What You Expected

no crash  using the latest version of fabric api

### What Happened Instead

crash

### Additional Details

using the required version of fabric api to run TF crashes other mods

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by itsdinkd** [comment] 2022-06-14 01:31
waited 15+ days for the create fix and of course this happens :D

**Comment by itsdinkd** [comment] 2022-06-14 01:36
Ah just kidding. The create issue wasn't even fixed in this update. lol.

**Closed** 2022-06-14 04:22 UTC
Labels: bug

**Comment by HellishINC** [comment] 2022-06-14 05:20
You can edit the "fabric.mod.json" inside the TF jar and add >= (what the commit does) if you want to play this mod but it does still indeed crash with create and/or terrablender.

**Comment by AndyXTJ** [comment] 2022-06-14 19:36
> You can edit the "fabric.mod.json" inside the TF jar and add >= (what the commit does) if you want to play this mod but it does still indeed crash with create and/or terrablender.

Tks for the info bro :D 
For non-experienced people with conding syntaxes, here's a quick tutorial how to do it to avoid crashes and troubleshooting like I had to: 
Open the twilight forest mod jar with a file viewer oyp such as WinRAR, 
open "fabric.mod.json" with a text editor oyp such as notepad
find "fabric": "X.XX.X", and replace exactly like this: ">=X.XX.X", so it accepts a version higher or equal to the one there. Atm that we're going around this, the default dependent version is 0.53.3, but it might change, so

(oyp = of your preference)

**Comment by itsdinkd** [comment] 2022-06-14 23:44
> You can edit the "fabric.mod.json" inside the TF jar and add >= (what the commit does) if you want to play this mod but it does still indeed crash with create and/or terrablender.

The main issue is that I cannot update create in my modpack, as well as other people using TF in theirs. It's been reported 10 days ago, when will it be uploaded to CF?

**Comment by Tamaized** [comment] 2022-06-14 23:54
Why are you using alpha builds in modpacks, that's your first mistake.

**Comment by HellishINC** [comment] 2022-06-15 20:04
I'd agree with you Tamaized for public packs, but for personal/private I'd argue it's fine.

Someone has to test stuff out to be able to report it right?

**Comment by Tamaized** [comment] 2022-06-15 20:07
For testing purposes yes, but for someone to complain that they cant update their pack. that's not testing.

**Comment by itsdinkd** [comment] 2022-06-15 22:19
> Why are you using alpha builds in modpacks, that's your first mistake.

I used your alpha build pre CF release and it worked just fine in a private server with my modpack. I think the issue is taking 10+ days to fix an issue, but yes ultimately if I knew this was going to be the delay, I would have never added it.

**Comment by itsdinkd** [comment] 2022-06-15 22:20
> For testing purposes yes, but for someone to complain that they cant update their pack. that's not testing.

1) it is testing. seeing how I opened up numerous bug reports. So you're welcome
2) It's not complaining about "can't update my pack", its that your is preventing another popular mod from being updated due to long delays in its development cycle.

**Comment by Tamaized** [comment] 2022-06-15 22:59
>  It's not complaining about "can't update my pack", I'm complaining that your mod is preventing another popular mod from being updated in my pack, along with all the crashes, due to long delays in its development cycle.

That's contradictory lol. Anyway this is going no where.
