### ISSUE TITLE
You're in Grave Danger crashes when something tries to break a grave

### ISSUE THREAD

**Issue by inuyasha8369** [TeamTwilight/twilightforest-fabric#149] opened 2022-12-26 07:23 UTC
### Fabric Loader Version

0.12.5

### Fabric API Version

0.59.1

### Twilight Forest Version

4.1.313

### Client Log

https://gist.github.com/inuyasha8369/7b7940608886034dcf22686cdd67e2d8

### Crash Report (if applicable)

https://gist.github.com/inuyasha8369/7b7940608886034dcf22686cdd67e2d8

### Steps to Reproduce

try to kill the hydra

### What You Expected

it working

### What Happened Instead

crashing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2022-12-26 07:31
this is caused by You're in Grave Danger. I don't think the fix was backported to 1.18. Cannot be fixed by us.

**Comment by TropheusJ** [comment] 2023-04-29 07:59
Seems the fix was backported in january.

**Closed by TropheusJ** 2023-04-29 07:59 UTC
Labels: bug
