### ISSUE TITLE
Twilight Forest Crashing randomly if I walk around in the forest

### ISSUE THREAD

**Issue by Aketoo** [TeamTwilight/twilightforest-fabric#137] opened 2022-11-12 19:07 UTC
### Fabric Loader Version

0.14.9-1.19.2

### Fabric API Version

0.62.0+1.19.2

### Twilight Forest Version

4.2.301

### Client Log

https://gist.github.com/Aketoo/5c02e0b026a5e285d4d1a0cf5e32226e

### Crash Report (if applicable)

https://gist.github.com/Aketoo/dcc67251a3a6b7fdaf1ea44dbc862d7d

### Steps to Reproduce

Step 1: Enter the Twilight Forest

Step 2: Walk around in the Forest

Step 3: Your game crashes after a random amount of time (does not happen instantly).

### What You Expected

At least not crashing while walking around the forest.

### What Happened Instead

My Minecraft crashed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment] 2022-11-12 19:12
Duplicate of #104 Twilight Forest is incompatible with c2me please remove the mod.

**Closed by AlphaMode** 2022-11-12 19:12 UTC
Labels: bug
