### ISSUE TITLE
Carpet spams "Failed to handle entity type" with TF

### ISSUE THREAD

**Issue by EvionFox** [TeamTwilight/twilightforest-fabric#168] opened 2023-01-29 02:35 UTC
### Fabric Loader Version

Fabricloader 0.14.12

### Fabric API Version

Fabric API 0.73.0 - 1.19.2

### Twilight Forest Version

1.19.2 - 4.2.333

### Client Log

https://gist.github.com/EvionFox/5de5dd820b02608bc5b84793b89810c5

### Steps to Reproduce

1) Player logs in after having logged out inside the Twilight Forest zone
2) Console begins filling with "Failed to handle entity type entity.twilightforest.*"
3) Server eventually puts out "[Server thread/WARN]: Can't keep up!" warning and restarts. No crash report is generated.

We had originally entered and looked around, and then the the othe player Zayydd was booted out due to a client error. We've been having some of those crop up today. He came back about 2 hours later and when he logged in was when the server errors occurred. Prior to that, it had been running smoothly.

### What You Expected

Ideally the entities should not spam the server into overloading. I'm not sure what causes this issue unfortunately.

### What Happened Instead

The server rebooted after being bombarded with entity errors. As shown in the provided Gist log, it starts around line 670+
Unfortunately no crash report is made due to the server just entering a reboot state.

### Additional Details

If it would help, this is the link to the modpack involved: https://www.curseforge.com/minecraft/modpacks/lynxsmp

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2023-01-31 03:31
This is caused by carpet. They map entity types to events [here](https://github.com/gnembon/fabric-carpet/blob/be3c7f267c2b9c16381080e0af683dfe9992b571/src/main/java/carpet/script/CarpetEventServer.java#L1017), but that will miss any entities registered after that class is loaded. I don't think this is a TF issue or fixable by us, report to carpet and link here.

**Comment by EvionFox** [comment] 2023-01-31 04:20
Thank you very much for your insight! I have submitted the bug to Carpet here: https://github.com/gnembon/fabric-carpet/issues/1647#issue-1563626369

**Comment by TropheusJ** [comment] 2023-04-29 00:05
Seems it was an issue with taterzens, fixed in 1.19.3.

**Closed by TropheusJ** 2023-04-29 00:05 UTC
Labels: bug
