### ISSUE TITLE
Possible incompatibility or horrendously broken armor ID

### ISSUE THREAD

**Issue by MommaMato** [TeamTwilight/twilightforest-fabric#116] opened 2022-08-23 23:51 UTC
### Fabric Loader Version

1,14.9

### Fabric API Version

0.57.0

### Twilight Forest Version

4.1.251

### Crash Report (if applicable)

https://gist.github.com/MommaMato/251ff0193a91f8ec692f02c7276f11b8

### Steps to Reproduce

1. Install cosmetic armors
2. Install Twilight forest
3. enter game (single player or multiplayer)
4. Equip armor FIREY ARMOR (namely headpeice and boots)
5. Crash.

### What You Expected

Most of the other armors work COMPLETELY fine, Firey however, decided to give anyone within render distance a hard crash, shown in the complete crash report.

### What Happened Instead

Well. We hard crashed, and it soft locked our friend until we force deleted the offending armor from their very being.

### Additional Details

-Noteably, we are using cosmetic armors, the Fabric 1.18.2 - 1.3.1 version which we assume caused the incompatibility issue, however, the problem comes when they crashed using the mod in a different server (of which may NOT have cosmetic armors, at all, but I am not personally sure) still it should be looked into since it is a bug that can completely softlock people from their worlds. (Optifine is not installed since we are using ORIGINS and Optifine is not compatable at ALL with Origins,)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment] 2022-08-24 00:54
Duplicate of #74 Please don't check the box "I have confirmed this issue is unique and has not been reported already." without checking.

**Closed by AlphaMode** 2022-08-24 00:54 UTC
Labels: bug
