### ISSUE TITLE
Twilight Forest--- Bound must be positive

### ISSUE THREAD

**Issue by mynedoctor** [TeamTwilight/twilightforest-fabric#169] opened 2023-01-29 21:42 UTC
### Forge Version

Fabric 1.19.2v13.5zip

### Twilight Forest Version

1.19.2-4.2.333

### Client Log

https://gist.github.com/mynedoctor/fccbca916271173e6cec063b78b1c931

### Crash Report (if applicable)

https://gist.github.com/mynedoctor/203c41e4f645da081e389402675162f4

### Steps to Reproduce

1. load into twighlight forest.
2. I ran south until i crashed.
3. issue encountered on 2 computers different accounts.

### What You Expected

I wouldnt have expected to crash 

### What Happened Instead

I crashed

### Additional Details

I can probably replicate via video if requested

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2023-01-31 02:59
duplicate of #140

**Closed by TropheusJ** 2023-01-31 02:59 UTC
Labels: bug
