### ISSUE TITLE
Minoshroom Crashing Game

### ISSUE THREAD

**Issue by AaronAce1** [TeamTwilight/twilightforest-fabric#68] opened 2022-06-05 06:23 UTC
### Fabric Loader Version

v0.14.5

### Fabric API Version

v0.63.4+1.18.2

### Twilight Forest Version

Twilight Forest - Fabric - MC 1.18.2 - 4.1.232

### Client Log

https://gist.github.com/AaronAce1/c92f4c7c4362ef92a22d70ca477c7199

### Crash Report (if applicable)

https://gist.github.com/AaronAce1/448dc1d3efb57dfeaba1fe876ca673b9

### Steps to Reproduce

1. Summon Minoshroom or Find Labyrinth
2. Attack or be attacked by Minoshroom

### What You Expected

Ability to kill Minoshroom

### What Happened Instead

Game crashing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment] 2022-06-05 07:05
Duplicate of #61

**Closed by AlphaMode** 2022-06-05 07:05 UTC
Labels: bug
