### ISSUE TITLE
Game crashes whenever entering the TF

### ISSUE THREAD

**Issue by RynusTheGuynus** [TeamTwilight/twilightforest-fabric#154] opened 2023-01-03 06:48 UTC
### Fabric Loader Version

0.14.11

### Fabric API Version

0.67.0+1.18.2

### Twilight Forest Version

4.1.268

### Crash Report (if applicable)

https://gist.github.com/RynusTheGuynus/95fa6abb0c3ffcaccad814ffe8d4cea2

### Steps to Reproduce

1. Create a portal to the TF
2. Enter the portal
3. Game crashes and will not load after this point in any world

### What You Expected

not to crash I guess

### What Happened Instead

I crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment] 2023-01-31 03:37
duplicate of #139

**Closed by TropheusJ** 2023-01-31 03:37 UTC
Labels: bug
